USE glowcareclinic;
ALTER TABLE treatment ADD COLUMN durasi VARCHAR(50) DEFAULT '60 Menit' AFTER kategori;
DELETE FROM treatment;
INSERT INTO treatment (nama, kategori, durasi, deskripsi_panjang, gambar_url, status, urutan) VALUES 
('Chemical Peeling for Acne', 'Acne & Clear Skin', '45 Menit', 'A medical-grade exfoliating treatment that clears clogged pores, reduces inflammation, and prevents future breakouts by accelerating skin cell turnover.', 'https://lh3.googleusercontent.com/aida/AP1WRLujcWTK1YfamF3eHf--CWGtP54Xzr0dTrLE8exQHKauv7eKwH2KxkMbnnn3OIFz0JRJqeOnnB-xvc52CXJSUSqxPB2J69eL-672gZbcLEOGQ1faLZu3z0fME6VNqzr7aF-y7jEAGq_BDgHZWjSSBEu9Go7Rg6rnA0f7EzGK6AWbnsTgw04nre3drE5RbTEC1S_FoSwq4CDa3F3mDmD2LeioYlPAdAN68ROAlZFVm7pOwq5Hw8gxLcpNk8g', 'Aktif', 1),
('Laser Rejuvenation', 'Anti-Aging', '60 Menit', 'Utilizes advanced light technology to stimulate deep collagen production, smoothing fine lines and improving overall skin texture for a youthful lift.', 'https://lh3.googleusercontent.com/aida/AP1WRLsPJyl7HOF3SjPtH3DnFi1KWFEAVlOleDBLe4gvFgym5RI_Zqum5X8UU836r2mFzoJ0VzCZnkDPLcRjXdZs08HKuU0qfehHrYnwsBTEwjk36qC4wpufYaC_1VROzG9D7E7WcUdlzdZb_kv-uXMPfm1oFkjwdFraiDNh3JXUWUt_H4pC1M4fCD6YpFlnP2r3CVISexxi90XPp-i11R2MuGqA_mGzAXCMhzOhgVVbm1Zj8CEeGxRQshhZFaE', 'Aktif', 2),
('Radiance Glow Infusion', 'Brightening', '30 Menit', 'An instant brightening protocol delivering high-potency Vitamin C and antioxidants directly into the skin for a luminous, "glass skin" finish.', 'https://lh3.googleusercontent.com/aida/AP1WRLud5JcN3HE1jiekquCioe1ZLUPxj2_XjXsPqABFdT3YOx4in9KZfmV6tnFO8o94Tw_Tv-6HbymNXd3o9F8PbN7lh16sDHOObVwBHrFiqvWvOLRgvCPX-v21WIXMFW4RySvQ_V5JNOExZMaVg37AzsyREI2m6amKdnnLJKgAskeK3Pa-Z2EBHDnaHtYckLx22zxjSCEaQKJhX98dRxQ9s3dqrjTG9_a8UhfLBHvoa953o07EdLyLHvrmGg', 'Aktif', 3),
('Botox & Neuromodulators', 'Anti-Aging', '15 Menit', 'Precision injections that temporarily relax dynamic facial muscles, softening wrinkles and preventing deeper lines from forming.', 'https://lh3.googleusercontent.com/aida/AP1WRLvx9aMlJNEa5OJ5ldw2XnCFFOxAzy94gxGdXsSe1lEdli7kKExY3agiZmi7qEW4xBn9VW-2Zmrm8PUO4OuMO5CGJijvdki2ha6m5LbEoKG9SaMKQRv8rH9GG2GuVLkBs7wjcwvpfNBQIPEOhJ3KyTpEMPT9Y3tJVb6Flt-9zNdoyNFT4SGXMshDnKrF6zE4YhCLixCu9QAdbh8iPaywwCynpZhZEyLN7XGIyHQhxlr1LdFrsL9R4Tl164I', 'Aktif', 4),
('Pico Laser Toning', 'Brightening', '45 Menit', 'Advanced picosecond technology targeted at breaking down hyperpigmentation and melasma for an even, bright complexion with minimal downtime.', 'https://lh3.googleusercontent.com/aida/AP1WRLs8efS_KqoNh2DdtgQzoy7AeR07AAj5E7p6K2fpoW5uo0IMX7JyIFwj86nB2YODbODvxXED0SRmw4LZMA59HxGLyT7haxl5E4ylX4ass9oKmMPkuE4B0oc8_j9ucgGxN3gLXIwlS1azWjfpg962C7eqt5jI5c66i8vyuPBqgyKUpkBznvjPKjCrnZ868lad-UIl0vsdvAFmfk44gTV74Kuk-qPtfgFlmieoIBj2dAvFynnS-U6KV7plS3s', 'Aktif', 5),
('Clinical Hair Restoration', 'Hair & Body Care', '90 Menit', 'Evidence-based protocols to stimulate hair follicles and scalp health using bio-stimulatory infusions and light therapy.', 'https://lh3.googleusercontent.com/aida/AP1WRLuRS79_EeeqIF95-5-KbDYcCpVD9cU4cbHQgKQLWnZChHD3cXcpPFDcuggpBZzTlb6EJCjsg-FSufP0Tn7j6yMWlNRechDVUWQoswoDDiGrMjsHU9xb4Vb6dQG-leZ1nKbbtExVYiygZx2b_voH1nqCXxDEfY6501L8wc5QQS2XNHtY7POa2o757TvyRR35Yczjcbafd_BAzvWFmVB5ot6H2N-yZFLJomLputy7HcTCqvC_iteDjG-h5iQ', 'Aktif', 6),
('Laser Hair Removal', 'Hair & Body Care', '30 Menit', 'Permanent reduction of unwanted hair using medical-grade cooling lasers, safe for various skin tones and body areas.', 'https://lh3.googleusercontent.com/aida/AP1WRLt7aD1IKesYS9IkrsgX5JYFlGFnMSOC8tjyjNHWSIFnl9DRiQeGv-QCckQQwReJILrS-Uo_0YxXHryPfQE9IFw2DTanX9HWpRkufGpDblk6_NqZDRihmzfa7gCRuVGuQI-_koCU5n-LGd5mLgvcnDYTDHroN4LzUWDwMA9T-EQYQMQDTqZrosA-RdVPYkX68K7X3bwVl_Q1mk0ZKULjusilCofGCKDialBk6MEs5Oh-0k--tJubXNu0_hM', 'Aktif', 7),
('Medical Extraction Facial', 'Acne & Clear Skin', '60 Menit', 'A deep-cleansing medical protocol focused on professional manual extractions and sterile barrier repair for congested skin.', 'https://lh3.googleusercontent.com/aida/AP1WRLutb59GG4fLHfWTh8yM29VKRx3wez_vytddF8EFzPoUBUDIgga9kHGD5FBp2XIgwkRgd7soX1KP_KpZ50Rh3K31WzaZeZ1LbxsLNLSEVpGwQamEaULMUhgzY0o10ByB6jHN3rOC6f0aIYqBW3OBykOOLxTk7cuxa2RYreMC2k5kPFPh8BaNEW7POk2Gidb5aO5nsgZWj8jLKausEyBMdJA_aXiepMo9npxGPpgC1JtnlW7tvTeA21Ul2w', 'Aktif', 8),
('Dermal Filler Contouring', 'Anti-Aging', '45 Menit', 'Strategic volume restoration using hyaluronic acid to lift cheeks, define jawlines, and fill hollow areas for a balanced profile.', 'https://lh3.googleusercontent.com/aida/AP1WRLtLjJpm2g1F1Aw9OjOy3pnuvcOu7RebhwJbzTi2wYECjS6FTQd2VhE1ZnKe4rbVmmIwazHNlq7Ipf5y0Oy5pO-8o_0QEui7-QBdIV_UlC8kS0D3LwL2scoepJdeJITq2dDvEjiOLPjcwgm2IoDTP77sOmq5t6bW0a7jRpN0StBtvCCe9zUw-1AoxZno1Yx-mtwxsKhe50swwNBHbu9iqYH9m1RMk2NgSZ3mkFXeXgY6wwWZW0bcZFDTfQQ', 'Aktif', 9);
